### ISSUE TITLE
An error has occurred; please try again later. If you are the owner or the integrator of this website, please log into the back office to see the details of the error.

### ISSUE THREAD

**Issue by kursksait** [rapiddive/catchtheweb-barclay-epdq-payment-gateway#15]
After selecting the EPDQ payment, an error appears An error has occurred; please try again later on the page https://mdepayments.epdq.co.uk/ncol/test/orderstandard.asp. If you are the owner or the integrator of this website, please log into the back office to see the details of the error.. Nothing is visible in the logs, only BRAND too long : length 27 MAX:25.
Screenshots
[https://ibb.co/DW0hggN](https://ibb.co/DW0hggN)
[https://ibb.co/VH3cdJk](https://ibb.co/VH3cdJk)
[https://ibb.co/VByfBVc](https://ibb.co/VByfBVc)

**Comment by vinayshah** [comment]
hello @kursksait can you brands too long setting's page what brands are you adding to the settings

**Comment by kursksait** [comment]
Hi @vinayshah https://ibb.co/fXTykHt

**Comment by vinayshah** [comment]
@kursksait try reducing your brand Cards value to only 3, this can help.

**Comment by kursksait** [comment]
@vinayshah i tried it, but nothing changes

**Comment by kursksait** [comment]
Good time @vinayshah . When I remove 1 payment option and leave 3, I get an error in the epdq billing logs unknown order/1/s/

**Comment by elzette** [comment]
Hello @vinayshah - initially I received the same error `BRAND too long : length 40 MAX:25` and removed one to make it 3. 
Testing it again, I get the same error `unknown order/1/s/` as per @kursksait comment. Do you know perhaps why this could be or a solution. Thank you for your help.

**Comment by umahmadx** [comment]
hello @elzette - did you manage to solve this issue? i am facing the same issue and looking for help

**Comment by umahmadx** [comment]
Great News,
i managed to solve this issue by rearranging the parameters in correct alphabetical order and change 'PASWD' parameter to 'PSWD'     :)

**Comment by vinayshah** [comment]
@elzette @umahmadx @kursksait Please try the latest version from WordPress on your staging/dev env it should resolve the issue.
If still persist please open up the issue.
