### ISSUE TITLE
Error when testing Barclaycard EPDQ on Woocommerce

### ISSUE THREAD

**Issue by mervpayne** [rapiddive/catchtheweb-barclay-epdq-payment-gateway#16]
I'm getting what looks like a common error when testing Barclays EPDQ on Woocommerce.
It all seems to go through OK, the Barclays's site says the payment is authorised, but after a few seconds wait it goes to take me back to the website and then goes to this link:
https://www.amadihome.co.uk/wc-api/RapidDive_WC_Gateway_Barclay/
with the message: "There has been a critical error on this website."
I have found a solution from 2 years ago (change 'Default operation code' to 'sale' but this is still happening.
Do you know the best way to fix this please?
Thanks

**Comment by umahmadx** [comment]
hello mervpayne, did you manage to solve this weird problem? i am facing the same issue!

**Comment by vinayshah** [comment]
@mervpayne @umahmadx please try the latest master version, and also if you have any other fix please generate PR request.
Thanks,
